// <auto-generated />
using System;
using DesafioProduto.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioProduto.Data.Migrations
{
    [DbContext(typeof(DesafioProdutoContext))]
    [Migration("20251030210957_CraiarBanco")]
    partial class CraiarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioProduto.Dominio.Dominio.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("Favorito")
                        .HasColumnType("BIT");

                    b.Property<string>("LocalCompra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal?>("PrecoComDesconto")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("INT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR(40)");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Preco] * [QuantidadeProduto]", true);

                    b.Property<DateTime?>("UltimaVisualizacao")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Visualizacoes")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("tb_Produto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
